# General root path: http://localhost:18000/

version: '3.2'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=Ael7CaVu
    ports:
      - "15432:5432"
    volumes: 
      - ./tmp/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      args:
        - ADMIN_PWD=ieDai3mahgec
    restart: always
    ports:
      - "18001:8000"
    environment:
      - SECRET_KEY=ieN2tohzohwo7ohFongoh0Shaen3hioyeehuyubahw7efoopha
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://localhost:18000
      - DEBUG=0
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DB=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Ael7CaVu
      - STATIC_ROOT=./tmp/static
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - VUE_APP_API_ROOT=/api
    restart: always
    ports:
      - "18081:80"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine-slim
    restart: always
    ports:
      - "18000:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - backend
      - frontend
