version: '3.2'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=django_vue_template
      - POSTGRES_PASSWORD=DB_PWD-RND-S8-Ael7CaVu
      - POSTGRES_DB=django_vue_template
    ports:
      - "15432:5432"
    volumes: 
      - ./tmp/data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      args:
        - ADMIN_PWD=ADMIN_PWD-RND-S12-ieDai3mahgec
    restart: always
    ports:
      - "18001:8000"
    environment:
      - SECRET_KEY=SECRET_KEY-RND-S50-ieN2tohzohwo7ohFongoh0Shaen3hioyeehuyubahw7efoopha
      - ALLOWED_HOSTS=test.local
      - DEBUG=1
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DB=django_vue_template
      - DATABASE_USERNAME=django_vue_template
      - DATABASE_PASSWORD=DB_PWD-RND-S8-Ael7CaVu
      - STATIC_ROOT=./tmp/static
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "18081:80"
    depends_on:
      - backend
