version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5433:5432'
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=ieN2tohzohwo7ohFongoh0Shaen3hioyeehuyubahw7efoopha
      - DEBUG=1
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DB=django_vue_template
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456
      - STATIC_ROOT=./tmp/static
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8081:8080"
    environment:
      - VUE_APP_API_ROOT=http://localhost:8001/api
    depends_on:
      - backend
